In [8]:
# import the libraries

# linear algebra
import numpy as np  

# data processing
import pandas as pd 


# Data Visualization 
import matplotlib.pyplot as plt  
import seaborn as sns    


import os
import warnings

from IPython.display import display


from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [9]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [10]:
# Getting data from web

# dataset used from 
# url = "http://https://archive.ics.uci.edu/ml/machine-learning-databases/00352/"

data_subset = pd.read_excel("E:\\sample datasets\\Online Retail.xlsx", nrows=20000)

In [11]:
data_subset.head(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## Data Preperation

In [12]:
data = data_subset.copy()

In [14]:
data.shape

(20000, 8)

In [15]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [18]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
InvoiceNo      20000 non-null object
StockCode      20000 non-null object
Description    19929 non-null object
Quantity       20000 non-null int64
InvoiceDate    20000 non-null datetime64[ns]
UnitPrice      20000 non-null float64
CustomerID     13347 non-null float64
Country        20000 non-null object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 1.2+ MB

In [19]:
data.nunique()

InvoiceNo       938
StockCode      2408
Description    2362
Quantity        156
InvoiceDate     807
UnitPrice       207
CustomerID      559
Country          16
dtype: int64

In [20]:
data['Country'].value_counts()

United Kingdom    19012
Germany             256
France              197
Norway              147
EIRE                145
Portugal             80
Lithuania            35
Iceland              31
Italy                25
Australia            22
Japan                17
Belgium              12
Poland                8
Switzerland           6
Spain                 5
Netherlands           2
Name: Country, dtype: int64

In [25]:
# I will prepare recommendataions rules for United kingdom retail data.
# Seperating transactions for United Kingdom

data[data['Country']=='United Kingdom']['Country'].count()

19012

In [26]:
data[data['Country']=='United Kingdom']
.groupby(['InvoiceNo', 'Description'])['Quantity']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
19995,C537998,22725,ALARM CLOCK BAKELIKE CHOCOLATE,-4,2010-12-09 11:42:00,3.75,17411.0,United Kingdom
19996,537999,22034,NaN,-223,2010-12-09 11:44:00,0.00,NaN,United Kingdom
19997,538000,22942,CHRISTMAS LIGHTS 10 SANTAS,5,2010-12-09 11:44:00,8.50,12748.0,United Kingdom
19998,538000,79321,CHILLI LIGHTS,12,2010-12-09 11:44:00,4.95,12748.0,United Kingdom
19999,538001,35958,NaN,10,2010-12-09 11:45:00,0.00,NaN,United Kingdom

In [36]:
mybasket = data[data['Country']=='United Kingdom'].groupby(['InvoiceNo', 'Description'])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo')
mybasket.head()

Description,4 PURPLE FLOCK DINNER CANDLES,OVAL WALL MIRROR DIAMANTE,SET 2 TEA TOWELS I LOVE LONDON,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,ZINC FINISH 15CM PLANTER POTS,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE CHARGER LARGE,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,amazon,check,damages
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536366,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536367,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536368,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
536369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [38]:
# converting all positive values to 1 and everything else to 0

def my_encode_units(x):
    if x <=0:
        return 0
    if x >= 1:
        return 1

my_basket_sets = mybasket.applymap(my_encode_units)
my_basket_sets.head(3)

Description,4 PURPLE FLOCK DINNER CANDLES,OVAL WALL MIRROR DIAMANTE,SET 2 TEA TOWELS I LOVE LONDON,10 COLOUR SPACEBOY PEN,12 COLOURED PARTY BALLOONS,12 DAISY PEGS IN WOOD BOX,12 EGG HOUSE PAINTED WOOD,12 IVORY ROSE PEG PLACE SETTINGS,12 MESSAGE CARDS WITH ENVELOPES,12 PENCIL SMALL TUBE WOODLAND,...,ZINC FINISH 15CM PLANTER POTS,ZINC FOLKART SLEIGH BELLS,ZINC HEART LATTICE CHARGER LARGE,ZINC HEART LATTICE T-LIGHT HOLDER,ZINC METAL HEART DECORATION,ZINC TOP 2 DOOR WOODEN SHELF,ZINC WILLIE WINKIE CANDLE STICK,amazon,check,damages
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
536365,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536366,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
536367,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [44]:
my_basket_sets.columns

Index([' 4 PURPLE FLOCK DINNER CANDLES', ' OVAL WALL MIRROR DIAMANTE ',
       ' SET 2 TEA TOWELS I LOVE LONDON ', '10 COLOUR SPACEBOY PEN',
       '12 COLOURED PARTY BALLOONS', '12 DAISY PEGS IN WOOD BOX',
       '12 EGG HOUSE PAINTED WOOD', '12 IVORY ROSE PEG PLACE SETTINGS',
       '12 MESSAGE CARDS WITH ENVELOPES', '12 PENCIL SMALL TUBE WOODLAND',
       ...
       'ZINC FINISH 15CM PLANTER POTS', 'ZINC FOLKART SLEIGH BELLS',
       'ZINC HEART LATTICE CHARGER LARGE', 'ZINC HEART LATTICE T-LIGHT HOLDER',
       'ZINC METAL HEART DECORATION', 'ZINC TOP  2 DOOR WOODEN SHELF ',
       'ZINC WILLIE WINKIE  CANDLE STICK', 'amazon', 'check', 'damages'],
      dtype='object', name='Description', length=2338)

In [46]:
my_basket_sets.drop(['amazon', 'check', 'damages'], inplace=True, axis=1)

In [48]:
my_basket_sets.columns

Index([' 4 PURPLE FLOCK DINNER CANDLES', ' OVAL WALL MIRROR DIAMANTE ',
       ' SET 2 TEA TOWELS I LOVE LONDON ', '10 COLOUR SPACEBOY PEN',
       '12 COLOURED PARTY BALLOONS', '12 DAISY PEGS IN WOOD BOX',
       '12 EGG HOUSE PAINTED WOOD', '12 IVORY ROSE PEG PLACE SETTINGS',
       '12 MESSAGE CARDS WITH ENVELOPES', '12 PENCIL SMALL TUBE WOODLAND',
       ...
       'YOU'RE CONFUSING ME METAL SIGN ', 'YULETIDE IMAGES GIFT WRAP SET',
       'YULETIDE IMAGES S/6 PAPER BOXES', 'ZINC FINISH 15CM PLANTER POTS',
       'ZINC FOLKART SLEIGH BELLS', 'ZINC HEART LATTICE CHARGER LARGE',
       'ZINC HEART LATTICE T-LIGHT HOLDER', 'ZINC METAL HEART DECORATION',
       'ZINC TOP  2 DOOR WOODEN SHELF ', 'ZINC WILLIE WINKIE  CANDLE STICK'],
      dtype='object', name='Description', length=2335)

## Training Model

In [74]:
# Generating frequent item sets

my_frequent_itemsets = apriori(my_basket_sets, min_support=0.05, use_colnames=True)

In [72]:
my_frequent_itemsets.head(15)

     support itemsets
0   0.052109     (75)
1   0.052109     (97)
2   0.070720    (150)
3   0.070720    (489)
4   0.050868    (494)
5   0.060794    (758)
6   0.060794    (989)
7   0.116625    (990)
8   0.089330    (991)
9   0.078164    (993)
10  0.093052    (994)
11  0.109181    (995)
12  0.071960   (1025)
13  0.078164   (1026)
14  0.068238   (1056)

In [67]:
# Genarating rules

my_rules = association_rules(my_frequent_itemsets, metric='lift', min_threshold=1)

In [80]:
# viewing top rules
my_rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(HAND WARMER BIRD DESIGN),(HAND WARMER OWL DESIGN),0.116625,0.089330,0.053350,0.457447,5.120863,0.042932,1.678490
1,(HAND WARMER OWL DESIGN),(HAND WARMER BIRD DESIGN),0.089330,0.116625,0.053350,0.597222,5.120863,0.042932,2.193206
2,(HAND WARMER BIRD DESIGN),(HAND WARMER SCOTTY DOG DESIGN),0.116625,0.093052,0.054591,0.468085,5.030355,0.043738,1.705062
3,(HAND WARMER SCOTTY DOG DESIGN),(HAND WARMER BIRD DESIGN),0.093052,0.116625,0.054591,0.586667,5.030355,0.043738,2.137197
4,(HAND WARMER OWL DESIGN),(HAND WARMER SCOTTY DOG DESIGN),0.089330,0.093052,0.059553,0.666667,7.164444,0.051241,2.720844
5,(HAND WARMER SCOTTY DOG DESIGN),(HAND WARMER OWL DESIGN),0.093052,0.089330,0.059553,0.640000,7.164444,0.051241,2.529639
6,(KNITTED UNION FLAG HOT WATER BOTTLE),(RED WOOLLY HOTTIE WHITE HEART.),0.075682,0.093052,0.050868,0.672131,7.223169,0.043826,2.766191
7,(RED WOOLLY HOTTIE WHITE HEART.),(KNITTED UNION FLAG HOT WATER BOTTLE),0.093052,0.075682,0.050868,0.546667,7.223169,0.043826,2.038936
8,(PAPER CHAIN KIT 50'S CHRISTMAS ),(PAPER CHAIN KIT VINTAGE CHRISTMAS),0.106700,0.083127,0.053350,0.500000,6.014925,0.044480,1.833747
9,(PAPER CHAIN KIT VINTAGE CHRISTMAS),(PAPER CHAIN KIT 50'S CHRISTMAS ),0.083127,0.106700,0.053350,0.641791,6.014925,0.044480,2.493797

## Making recommendations

In [78]:
my_basket_sets['HAND WARMER BIRD DESIGN'].sum()

94

In [87]:
# filtering rules based on condition

my_rules[ (my_rules['lift'] >= 6) & (my_rules['confidence'] >= 0.5) ]

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
4,(HAND WARMER OWL DESIGN),(HAND WARMER SCOTTY DOG DESIGN),0.089330,0.093052,0.059553,0.666667,7.164444,0.051241,2.720844
5,(HAND WARMER SCOTTY DOG DESIGN),(HAND WARMER OWL DESIGN),0.093052,0.089330,0.059553,0.640000,7.164444,0.051241,2.529639
6,(KNITTED UNION FLAG HOT WATER BOTTLE),(RED WOOLLY HOTTIE WHITE HEART.),0.075682,0.093052,0.050868,0.672131,7.223169,0.043826,2.766191
7,(RED WOOLLY HOTTIE WHITE HEART.),(KNITTED UNION FLAG HOT WATER BOTTLE),0.093052,0.075682,0.050868,0.546667,7.223169,0.043826,2.038936
8,(PAPER CHAIN KIT 50'S CHRISTMAS ),(PAPER CHAIN KIT VINTAGE CHRISTMAS),0.106700,0.083127,0.053350,0.500000,6.014925,0.044480,1.833747
9,(PAPER CHAIN KIT VINTAGE CHRISTMAS),(PAPER CHAIN KIT 50'S CHRISTMAS ),0.083127,0.106700,0.053350,0.641791,6.014925,0.044480,2.493797

In [ ]:
# Recommendations can be made with higher lift values
# i.e example if X buys 'RED WOOLLY HOTTIE WHITE HEART.', then he is more likely to buy 'KNITTED UNION FLAG HOT WATER BOTTLE'